name: Test

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v7
    - uses: astral-sh/ruff-action@v3
    - run: uvx --with-editable . pytest tests
    - run: cat pyproject.toml | uvx --from validate-pyproject[all,store] validate-pyproject
